spring:
  # Setup Embedded Services: Artemis, H2 Database
  artemis:
    mode: embedded
    broker-url: tcp://localhost:61617
    user: artemis
    password: artemis
    embedded:
      server-id: 54321
      enabled: true
      queues: test.queue1
  jms:
    template:
      default-destination: default.queue
    pub-sub-domain: false
  sql:
    init:
      mode: embedded
      platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: true

server:
    port: 8081

management:
  server:
    port: 8086
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - camel
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    camel:
      enabled: true

gwh:
  service:
    # profile: dispatcher
    # profile: ftptestprofile
    profile: ftptest2
    region: ALL
  properties:
    db:
      table: properties
      keyColumn: property_key
      valueColumn: property_value
      profileColumn: profile
      url: jdbc:h2:mem:gwh;INIT=RUNSCRIPT FROM 'classpath:schema-h2.sql'\;RUNSCRIPT FROM 'classpath:data-h2.sql';
      userName: pwaldorf
      password: pwaldorf

#  framework:
#    load:
#      properties:
#        core1:
#          enabled: false
#        jpa1:
#          enabled: false
#      routes:
#        core1:
#          enabled: true
#        jpa1:
#          enabled: true
#      routetemplates:
#        core1:
#          enabled: true
#        jpa1:
#          enabled: true
#      caches:
#        core1:
#          enabled: true
#        jpa1:
#          enabled: true
#    core:
#      routemanagement:
#        enabled: true
#    component:
#      activemq:
#        default1:
#          default:
#            enabled: true
#          consumer:
#            enabled: true
#          producer:
#            enabled: true
#      kafka:
#        default1:
#          default:
#            enabled: true
#          consumer:
#            enabled: true
#          producer:
#            enabled: true
#      ftp:
#        default1:
#          consumer:
#            enabled: true
#      pgpencryption:
#        default1:
#          enabled: false
#      routemanagement:
#        rest1:
#          enabled: true

#  component:
#    ftp:
#      default1:
#        consumer:
#          protocol: ftp
#    activemq:
#      default1:
#        broker-url: tcp://localhost:61617
#        username: artemis
#        password: artemis
#        session-cache-size: 10
#
#    kafka:
#      default1:
#        consumer-brokers: 192.168.6.50:9093
#        producer-brokers: 192.168.6.50:9093

#    pgp:
#      default1:
#        publicKeyUserId: 'pw company <philip.waldorf@gmail.com>'
#        publicKeyPassword: XXXXXXXX
#        publicKeyFileName: 'file:/home/pwaldorf/.gnupg/pubring.gpg'
#        privateKeyUserId: 'pw company <philip.waldorf@gmail.com>'
#        privateKeyPassword: XXXXXXXX
#        privateKeyFileName: 'file:/home/pwaldorf/.gnupg/secring.gpg'

#  db:
#    datasource:
#      className: org.h2.Driver
#      url: jdbc:h2:mem:gwh
#      userName: pwaldorf
#      password: pwaldorf
#      minpoolsize: 0
#      maxpoolsize: 50
#      increment: 2
#      maxidleTime: 300
#      retryDelay: 600000
#      databaseType: H2
#      jpa-dialect: org.hibernate.dialect.H2Dialect
#      jpa-ddl-auto: validate
#      jpa-physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#      jpa-properties:
#        hibernate:
#          hbm2ddl:
#            auto: validate
#          physical:
#            naming:
#              strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

camel:
  servlet:
    mapping:
      context-path: /api/*
  main:
    dev-console-enabled: true
  springboot:
    name: GWH
   # tracing-standby: true
   # tracing: true
    dev-console-enabled: true

logging:
  level:
    org:
      apache:
        camel: INFO
      springframework:
       transaction:
         interceptor: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
            BasicBinder: TRACE
      activemq:
        audit:
          base: INFO
          message: INFO